// scripts/build-pieces.ts
import fs from 'fs';
import path from 'path';
import sharp from 'sharp';

const PIECES_DIR = './src/assets/pieces';
const OUTPUT_FILE = './src/utils/toolkit/pieceSprites.ts';

// Grid Layout: 6 pieces wide, 2 colors tall
const PIECE_ORDER = ['K', 'Q', 'R', 'B', 'N', 'P'];
const COLORS = ['w', 'b'];
const TILE_SIZE = 128; // 128px per piece gives crisp resolution on mobile without bloating file size

async function buildSpritesheets() {
  const themes = fs.readdirSync(PIECES_DIR).filter(f => fs.statSync(path.join(PIECES_DIR, f)).isDirectory());
  const sprites: Record<string, string> = {};

  for (const theme of themes) {
    const themeDir = path.join(PIECES_DIR, theme);
    const compositeOperations = [];

    for (let row = 0; row < COLORS.length; row++) {
      for (let col = 0; col < PIECE_ORDER.length; col++) {
        // Look for the piece, ignoring case and leading underscores (e.g. "_wP.svg" or "wp.svg")
        const targetPiece = `${COLORS[row]}${PIECE_ORDER[col]}`.toLowerCase();
        const files = fs.readdirSync(themeDir);
        const file = files.find(f => f.toLowerCase().includes(targetPiece) && f.endsWith('.svg'));

        if (file) {
          const svgBuffer = fs.readFileSync(path.join(themeDir, file));
          // Resize SVG to a standard square
          const resized = await sharp(svgBuffer).resize(TILE_SIZE, TILE_SIZE).toBuffer();

          compositeOperations.push({
            input: resized,
            top: row * TILE_SIZE,
            left: col * TILE_SIZE,
          });
        }
      }
    }

    const width = PIECE_ORDER.length * TILE_SIZE;
    const height = COLORS.length * TILE_SIZE;

    // Create the transparent WebP canvas and layer the pieces
    const spriteBuffer = await sharp({
      create: { width, height, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } }
    })
      .composite(compositeOperations)
      .webp({ quality: 80 }) // Compress to WebP
      .toBuffer();

    sprites[theme] = `data:image/webp;base64,${spriteBuffer.toString('base64')}`;
  }

  // Generate the output TS file
  const tsContent = `// AUTO-GENERATED BY build-pieces.ts\nexport const pieceSprites: Record<string, string> = ${JSON.stringify(sprites, null, 2)};\n`;
  fs.writeFileSync(OUTPUT_FILE, tsContent);
  console.log(`Successfully generated WebP sprites for ${themes.length} themes.`);
}

buildSpritesheets();
